[package]
name = "level"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.17.3"
enemy = { path = "../enemy" }
models = { path = "../models" }
combat = { path = "../combat" }
castle = { path = "../castle" }
bevy_rapier2d  = "0.32.0"
