[package]
name = "combat"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.16.1"
models = { path = "../models" }
castle = { path = "../castle" }
bevy_rapier2d  = "0.31.0"
derive_more = { version = "2.1.0", features = ["full"] }
